=== mvreeuwijk/Nobius/validation/schemas/question.json
{
"$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for question.json file.",
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "master_statement": {"type": "string"},
        "media": {
            "type": "array",
            "items": {"type": "string"}
        },
        "icon_data": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer",
                    "enum": [1, 2, 3]
                },
                "par_time": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",
                        "minimum": 0
                    }
                },
                "statement": {"type": "string"}
            },
            "required": [
                "difficulty",
                "par_time"
            ]
        },
        "parts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "statement": {"type": "string"},
                    "media": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "input_symbols": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "response": {"type": "object"},
                    "responses": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "object"}
                    },
                    "custom_response": {
                        "type": "object",
                        "properties": {
                            "layout": {"type": "string"},
                            "responses": {"type": ["array", "object"]}
                        }
                    },
                    "final_answer": {
                        "type": "object",
                        "properties": {
                            "text": {"type": "string"},
                            "equation": {"type": "string"},
                            "media": {
                                "type": "array",
                                "items": {"type": "string"}
                            }
                        }
                    },
                    "worked_solutions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string"},
                                "equation": {"type": "string"},
                                "media": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                },
                                "is_final_answer": {
                                    "type": "boolean",
                                    "const": true
                                }
                            }
                        }
                    },
                    "structured_tutorial": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string"},
                                "h5p_link": {"type": "string"},
                                "media": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                },
                                "response": {"type": "object"},
                                "responses": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {"type": "object"}
                                },
                                "custom_response": {
                                    "type": "object",
                                    "properties": {
                                        "layout": {"type": "string"},
                                        "responses": {"type": ["array", "object"]}
                                    }
                                }
                            }
                        }
                    },
                    "pre_response_text": {"type": "string"},
                    "post_response_text": {"type": "string"}
                },
                "required": ["statement"],
                "allOf": [
                    {
                        "if": {"required": ["response"]},
                        "then": {"properties": {"responses": false}}
                    },
                    {
                        "if": {"required": ["responses"]},
                        "then": {"properties": {"response": false}}
                    }
                ]
            }
        },
        "uid": {"type": "string"},
        "algorithm": {"type": "string"},
        "adaptive": {
            "type": "object",
            "properties": {
                "enabled": {"type": "boolean"},
                "notes": {"type": "string"}
            },
            "required": ["enabled"]
        }
    },
    "required": [
        "title",
        "parts",
        "uid"
    ]
}

=== mvreeuwijk/Nobius/tests/fixtures/RoundTrip/Numerical.json
{
    "title": "Numerical",
    "algorithm": "  $a = range(10,20);\n$b = range(0, 10);\n$c = $a + $b  ",
    "uid": "7c3b4542-978a-4202-abeb-b0aff3bf3abe",
    "master_statement": "If a=$a and b=$b, what is c?",
    "parts": [
        {
            "statement": "",
            "response": {
                "mode": "Numeric",
                "name": "responseNaN",
                "answer": {
                    "num": "$c",
                    "units": ""
                },
                "grading": "exact_value",
                "showUnits": false,
                "negStyle": "minus",
                "numStyle": "thousands scientific  arithmetic",
                "comment": ""
            }
        }
    ]
}

=== mvreeuwijk/Nobius/tests/fixtures/t01/Density02.json
{
   "title": "Varying Density in a Truncated Cone",
   "icon_data": {
      "difficulty": 3,
      "par_time": [
         20,
         30
      ],
      "statement": ""
   },
   "master_statement": "Using the geometries of the previous question, calculate the mass of the fluid if the fluid density varies linearly according to \\(\\rho(z)=\\rho_{0}-a z\\)",
   "media": [
      "TruncatedCone.png"
   ],
   "parts": [
      {
         "statement": "",
         "response": {
            "mode": "Non Permuting Multiple Choice",
            "answer": 3,
            "choices": [
               "<p>\\(W=\\frac{1}{3} \\rho_{0} g \\pi h\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-R_{t} R_{0}\\right\\}+\\frac{1}{4} \\operatorname{ag\\pi h}^{2}\\left\\{\\left(R_{t}+R_{0}\\right)^{2}+\\frac{2}{3}\\left(R_{t} R_{0}+R_{0}^{2}\\right)\\right\\}\\)</p>",
               "<p>\\(W=\\frac{1}{4} \\operatorname{ag\\pi h}^{2}\\left\\{\\frac{2}{3}\\left(R_{t} R_{0}+R_{0}^{2}\\right)-\\left(R_{t}+R_{0}\\right)^{2}\\right\\}-\\frac{1}{3} \\rho_{0} g \\pi h\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-R_{t} R_{0}\\right\\}\\)</p>",
               "<p>\\(W=\\frac{1}{3} \\rho_{0} g \\pi h\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-R_{t} R_{0}\\right\\}-\\frac{1}{4} \\operatorname{ag\\pi h}^{2}\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-\\frac{2}{3}\\left(R_{t} R_{0}+R_{0}^{2}\\right)\\right\\}\\)</p>",
               "<p>\\(W=\\frac{1}{4} \\operatorname{ag\\pi h}^{2}\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-\\frac{2}{3}\\left(R_{t} R_{0}+R_{0}^{2}\\right)\\right\\}-\\frac{1}{3} \\rho_{0} g \\pi h\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-R_{t} R_{0}\\right\\}\\)</p>"
            ]
         },
         "final_answer": {
            "text": "\\(W=\\frac{1}{3} \\rho_{0} g \\pi h\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-R_{t} R_{0}\\right\\}-\\frac{1}{4} \\operatorname{ag\\pi h}^{2}\\left\\{\\left(R_{t}+R_{0}\\right)^{2}-\\frac{2}{3}\\left(R_{t} R_{0}+R_{0}^{2}\\right)\\right\\}\\)"
         },
         "worked_solutions": [
            {
               "text": "If the density of the fluid varies linearly according to : <br>\\(\\rho(z)=\\rho_{0}-a z\\)"
            },
            {
               "text": "The weight of the fluid is given as: <br>\\(\\begin{aligned}W &=\\int_{0}^{h}\\left(\\rho_{0}-a z\\right) g \\pi\\left\\{\\frac{R_{t}-R_{0}}{h} z+R_{0}\\right\\}^{2} d z \\\\&=\\rho_{0} g \\pi \\int_{0}^{h}\\left\\{\\left(\\frac{R_{t}-R_{0}}{h}\\right)^{2} z^{2}+2 \\frac{R_{0}}{h}\\left(R_{t}-R_{0}\\right) z+R_{0}^{2}\\right\\} d z\\\\&-a g \\pi \\int_{0}^{h}\\left\\{\\left(\\frac{R_{t}-R_{0}}{h}\\right)^{2} z^{3}+2 \\frac{R_{0}}{h}\\left(R_{t}-R_{0}\\right) z^{2}+R_{0}^{2} z\\right\\} d z\\\\&=\\rho_{0} g \\pi\\left\\{\\left(\\frac{R_{t}-R_{0}}{h}\\right)^{2} \\frac{1}{3} z^{3}+\\frac{R_{0}}{h}\\left(R_{t}-R_{0}\\right) z^{2}+\\left.R_{0}^{2} z\\right|_{0} ^{h}\\right\\}\\&-a g \\pi\\left\\{\\frac{1}{4}\\left(\\frac{R_{t}-R_{0}}{h}\\right)^{2} z^{4}+\\frac{2}{3} \\frac{R_{0}}{h}\\left(R_{t}-R_{0}\\right) z^{3}+\\left.\\frac{R_{0}^{2}}{2} z^{2}\\right|_{0} ^{h}\\right\\}\\&W=\\rho_{0} g \\pi h\\left\\{\\frac{1}{3} R_{t}^{2}+\\frac{1}{3} R_{t} R_{0}+\\frac{1}{3} R_{0}^{2}\\right\\}-a g \\pi h^{2}\\left\\{\\frac{1}{4} R_{t}^{2}+\\frac{1}{6} R_{t} R_{0}+\\frac{1}{12} R_{0}^{2}\\right\\}\\end{aligned}\\)"
            },
            {
               "is_final_answer": true
            }
         ]
      }
   ],
   "uid": "fd7a8638-fcfe-42f1-a591-5690cc832ebf"
}

=== mvreeuwijk/Nobius/tests/fixtures/RoundTrip/Symbolic.json
{
    "title": "Symbolic",
    "uid": "f4de05e1-7b98-4f60-baf3-68a25a52a869",
    "master_statement": "Give the equation for the area of a Circle in terms of its diameter D?",
    "parts": [
        {
            "statement": "",
            "response": {
                "mode": "Maple",
                "name": "responseNaN",
                "mapleAnswer": "Pi/4*D^2",
                "maple": "evalb(($ANSWER)-($RESPONSE)=0);",
                "type": "maple",
                "allow2d": 0,
                "mathConversionMode": 0,
                "comment": ""
            }
        }
    ]
}

=== mvreeuwijk/Nobius/tests/fixtures/RoundTrip/Numerical-20260408_220141.json
{
    "title": "Numerical-20260408_220141",
    "uid": "59320b45-5b9d-4768-bd09-8ff784864ac5",
    "master_statement": "What is the gravitational acceleration on Earth in m/s^2?",
    "parts": [
        {
            "statement": "",
            "response": {
                "mode": "Numeric",
                "name": "sro_id_1",
                "answer": {
                    "num": "9.81",
                    "units": ""
                },
                "grading": "toler_abs",
                "err": 0.01,
                "showUnits": false,
                "negStyle": "minus",
                "numStyle": "thousands scientific  arithmetic",
                "comment": ""
            }
        }
    ]
}

=== mvreeuwijk/Nobius/tests/fixtures/TemplateQuestions/MultipleChoice.json
{
   "title": "Multiple Choice (Q2.2)",
   "icon_data": {
      "difficulty": 1,
      "par_time": [
         10,
         15
      ],
      "statement": ""
   },
   "master_statement": "A stagnant reservoir is stably stratified with two immiscible liquids of density \\(\\rho_{1}\\)and \\(\\rho_{2}\\) where \\(\\rho_{1} > \\rho_{2}\\), respectively. Which graph below depicts correctly the distribution of gauge pressure along a vertical line through the liquids.",
   "media": [
      "ResevoirGaugePressure.png"
   ],
   "parts": [
      {
         "statement": "",
         "response": {
            "mode": "Non Permuting Multiple Choice",
            "answer": 2,
            "choices": [
               "i",
               "ii",
               "iii",
               "iv"
            ]
         }
      }
   ],
   "uid": "003e659f-eb4a-4500-ba21-9afef9a2f110"
}

=== mvreeuwijk/Nobius/tests/fixtures/TemplateQuestions/AlgorithmicAnswer.json
{
   "title": "",
   "icon_data": {
      "difficulty": 1,
      "par_time": [
         10,
         15
      ],
      "statement": ""
   },
   "master_statement": "",
   "media": [
      ""
   ],
   "parts": [
      {
         "statement": "",
         "response": {
            "mode": "Numeric",
            "showUnits": true,
            "grading": "toler_perc",
            "perc": 5,
            "answer": {
               "num": "",
               "units": ""
            }
         },
		 "final_answer": {
            "text": ""
         },
         "worked_solutions": [
            {
               "text": ""
            }
         ]
      }
   ],
   "algorithm": "",
   "uid": ""
}

=== mvreeuwijk/Nobius/tests/fixtures/TemplateQuestions/AlgorithmicAnswer03.json
{
   "title": "Algorithmic Answer 3 (Q9.4)",
   "icon_data": {
      "difficulty": 1,
      "par_time": [
         10,
         15
      ],
      "statement": ""
   },
   "master_statement": "You are asked to design a pipeline between two reservoirs, of which the first is $h m higher than the second. The reservoirs are $s km far apart and should carry a discharge of $Q \\(m^{3}/s\\). Calculate the design diameter D of the pipe. Assume that the pipe roughness is such that the friction coefficient f=0.02. Hint: neglect the exit loss. Verify afterwards if thisassumption was justified.",
   "parts": [
      {
         "statement": "",
         "response": {
            "mode": "Numeric",
            "showUnits": true,
            "grading": "exact_sigd",
            "digit": 3,
            "answer": {
               "num": "$d",
               "units": "m"
            }
         },
		 "final_answer": {
            "text": "$d m"
         },
         "worked_solutions": [
            {
               "media": [
					"HydraulicJumpCV.png"
				]
            },
            {
               "text": "Apply Bernoulli along a streamline between 1 and 3, including frictional losses but neglecting the exit loss:<br> \\(H_{1}=H_{3}+\\Delta H_{1}=H_{3}+f \\frac{U_{2}^{2}}{2 g} \\frac{L}{D}\\)"
            },
            {
               "text": "\\(\\overbrace{H_{1}-H_{3}}^{\\Delta H}=\\frac{U_{2}^{2}}{2 g} f \\frac{L}{D}\\)"
            },
            {
               "text": "Using that \\(Q=U_{2} A_{2}=U_{2} \\frac{1}{4} \\pi D^{2}\\) and thus \\(U_{2}=\\frac{4 Q}{\\pi D^{2}}\\) results in:<br>\\(\\Delta H=\\frac{16 f L Q^{2}}{2 \\pi^{2} g D^{5}}\\)"
            },
			{
               "text": "\\(D=\\sqrt[5]{\\frac{8 f L Q^{2}}{\\pi^{2} g \\Delta H}}\\)"
            },
			{
				"is_final_answer": true
			}
         ]
      }
   ],
   "uid": "3b8b78d8-3368-440b-ae47-0b5ba1cd4563"
}

=== mvreeuwijk/Nobius/tests/fixtures/t01/Starter.json
{
	"title": "Fluids",
	"icon_data": {
		"difficulty": 1,
		"par_time": [
			10,
			15
		],
		"statement": ""
	},
	"master_statement": "After entering your answer, check the help box to check your work.",
	"parts": [
		{
			"statement": " Define (unambiguously) a fluid.",
			"response": {
				"mode": "List",
				"display": {
					"display": "text",
					"permute": false
				},
				"grader": "regex",
				"answers": [
					"~~~~~~~~~~Check the help box to get the answer~~~~~~~~~~",
					".*"
				],
				"credits": [
					1,
					0.9999999
				]
			},
			"final_answer": {
				"text": "A substance that deforms continuously under the application of shear stress"
			}
		},
		{
			"statement": "Fluids are all around you in everyday life, give examples.",
			"response": {
				"mode": "List",
				"display": {
					"display": "text",
					"permute": false
				},
				"grader": "regex",
				"answers": [
					"~~~~~~~~~~Check the help box to get the answer~~~~~~~~~~",
					".*"
				],
				"credits": [
					1,
					0.9999999
				]
			},
			"final_answer": {
				"text": "Air, water, yogurt, petrol, diesel, oil, natural gas(methane), beer, wine, beverages in general, helium, treacle, blood, sweat, tears, sperm, snake poison, vacinations, etc"
			}
		},
		{
			"statement": "How do the fluids identified above differ? Contrast by comparing their physical properties, e.g.viscosity, density. [Give units in each case]",
			"response": {
				"mode": "List",
				"display": {
					"display": "text",
					"permute": false
				},
				"grader": "regex",
				"answers": [
					"~~~~~~~~~~Check the help box to get the answer~~~~~~~~~~",
					".*"
				],
				"credits": [
					1,
					0.9999999
				]
			},
			"final_answer": {
				"text": "- density differ: \\([\\rho ]=\\frac{M}{{L}^{3}}\\) <br> - viscosity differ: \\([\\mathcal{M}]=\\frac{M}{LT}\\)<br> - composition differs: e.g. air is composed of nitrogen(78%), oxygen(21%), Argon(0.4%), Carbon Dioxide(0.04%), etc."
			}
		}
	],
	"uid": "2fbdb33a-ac27-4f10-b22c-96bb66272a01"
}
