=== mvreeuwijk/Nobius/validation/schemas/sheet_info.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Schema for SheetInfo.json file.",
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "number": {"type": "integer"},
            "description": {"type": "string"},
            "questions": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 1
            },
            "uid": {"type": "string"},
            "media_folder": {"type": "string"}
        },
        "required": [
            "name",
            "number",
            "description",
            "questions",
            "uid"
        ]
    }

=== mvreeuwijk/Nobius/tests/fixtures/t02/SheetInfo.json
{
   "name": "Fluid Statics 1",
   "description": "!!! Empty Description from TexConverter !!!",
   "questions": [
      "Q1-HydraulicPress",
	  "Q2-ContainerDensity",
      "Q3-Resevoir",
      "Q4-TankLevel",
      "Q5-ComplexTankPressure",
      "Q6-FreebodyDiagram01",
      "Q7-FreebodyDiagram02"
   ],
   "number": 2,
   "uid": "09e5788a-8f60-4518-8937-c67ff00be1c1"
}

=== mvreeuwijk/Nobius/tests/fixtures/TemplateQuestions/SheetInfo.json
{
   "name": "Question Type Demos",
   "description": "!!! Empty Description from TexConverter !!!",
   "questions": [
      "TextAnswer",
      "MultipleChoice",
	  "WhatsIncorrect01",
	  "WhatsIncorrect02",
	  "AlgorithmicAnswer",
	  "AlgorithmicAnswer02",
	  "AlgorithmicAnswer03",
	  "SymbolicEquations",
	  "MatrixResponse",
	  "CombinedQuestion"
   ],
   "number": 5,
   "uid": "ce750ea8-92dd-44dc-8d0b-05e2b674f161"
}

=== mvreeuwijk/Nobius/tests/fixtures/RoundTrip/SheetInfo.json
{
  "name": "Round Trip Demo",
  "description": "",
  "uid": "16338682-fcc3-4972-8bc1-2f702fdfdbd5",
  "questions": [
    "Multiple selection problem",
    "Multipart hybrid exercise",
    "Numerical-20260408_220141",
    "Multiple Choice-20260408_220141",
    "Text Entry-20260408_220141",
    "Symbolic",
    "Numerical",
    "Essay-20260408_220141",
    "True False-20260408_220141",
    "Matching-20260408_220141"
  ],
  "number": 1
}
